### ISSUE TITLE
Open in "new", not in "same" tab

### ISSUE THREAD

**Issue by serapath** [t9md/atom-project-find-navigation#2]
Hey, I'm using the plugin, but it behaves differently than on the screenshot.
It opens each clicked search result in a new tab in the pane next to where the search results tab is.

What I was hoping for is
- that when I click or move to a result in the search results tab, it shows the file content in a "preview tab"
- when i double click (or something like that) a result, it opens the file content in a "tab" that will stay.

Currently every search result opens the file content in a new tab, which means I'm opening a lot of tabs if I want to take a look at a lot of entries in the search result tab, which eventually slows down my editor.

**Comment by t9md** [comment]
Whether opened file become preview tab or not is completely out of scope of this monkey patching package.
I understand what you want, but won't implement.
Preview state is handled in tree-view.
I don't want widen the area this monkey patch package need to cover.

I can consider if you send me PR for this feature.

**Comment by t9md** [comment]
Sorry I can't understand that you saying different behavior from screencast.

It should be same. One you open a file, following search target on same file just scroll to target position, not opening same file again and again.

If the behavior you see is different, I want to know that, and operation, keymap settings of your editor.

**Comment by serapath** [comment]
If I click the same `search result` it focuses the same tab, but for each clicked `search result`, it opens a separate tab. Would be nice if it would always show the content in the same "preview tab" and once i for example "double click", it could open a tab showing the `search result content` permanently.

The preview gif in your package description shows the "preview tab" getting updated when switching the clicked/focused `search result` instead of opening a new seperate tab showing the `search result content`

**Comment by t9md** [comment]
Preview or non-preview is handled by core tabs package.
 I also fixed the issue the opend pane was not appropriate when focus wasn't on result pane.
So I believe you no longer see odd behavior.
As long as your search result position is in **same file**, it open target on same tab.
Where reusing same tab for different file is depending on **preview state** of already opend file, which state is again not handled by this monkey patching package.

I will close this, if you still experience odd behavior I'll re-open then.

**Comment by serapath** [comment]
hey thx :-)
nice job by the way ;-)
