### ISSUE TITLE
Feature request: global next-result and previous-result bindings?

### ISSUE THREAD

**Issue by bronson** [t9md/atom-project-find-navigation#4]
I tried putting this in my cson:

``` cson
'body':
  'cmd-ctrl-n': 'project-find-navigation:select-next-and-confirm'
  'cmd-ctrl-p': 'project-find-navigation:select-prev-and-confirm'
```

But those commands only work when the project find dialog is focused.

Any chance I could hit `cmd-ctrl-n` to jump to the next project find result?  I figure it would be the equivalent of focusing the dialog, selecting the next (or previous) item, and hitting return.

**Comment by t9md** [comment]
Maybe it could, I will try.
But if you close the result pane this command won't work.
Only available as long as result pane was open.
Is this fit your use case?

**Comment by bronson** [comment]
Yes!  If there are no results, there's nothing to jump to.

Right now I'm playing around with putting a compound command in my init.coffee...  seems doable but not so easy so far.

**Comment by t9md** [comment]
Ok. Will do.

**Comment by t9md** [comment]
Released!

**Comment by bronson** [comment]
Just noticing that the `'atom-workspace atom-text-editor:not([mini])'` selector doesn't work in the tree view or (amusingly) the project find results...  `'body'` does.

**Comment by t9md** [comment]
So can you close? Or something you want to change?

**Comment by bronson** [comment]
Actually, matching the same selector as activate-results-pane seems to give me exactly what I want.  `project-find-navigation:next` even works in the project find tab.

https://github.com/bronson/dotfiles/blob/89557207d8ce6beda1816fb36c1a23288a5f6660/.atom/keymap.cson#L42-L45

Phenomenal!!  Triumphantly closing.
