### ISSUE TITLE
The preview window remains open after closing.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-project-find-navigation#6]
After I close the search results area `q`, the preview window remains open.
I did not see any errors in the console. I'm on the latest beta `1.11.0`.

**Comment by t9md** [comment]
Me too use beta but have no issue.
I can close preview window by `q`.

To narrow-down the cause. 
- This package map `q` to `core:close` on preview-pane.
  https://github.com/t9md/atom-project-find-navigation/blob/master/keymaps/keymap.cson#L7
- Set focus on preview window and manualy invoke `Core Close` from command-palette.
- If you can close buffer, it's possibly keymap issue where `q` is overridden by other package?

```
% atom-beta --version
Atom    : 1.11.0-beta3
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

```

The previ

**Comment by jordwalke** [comment]
Manually invoking core:close on the preview does close the preview. I don't have any `q` mappings in my keyboard shortcuts though

**Comment by t9md** [comment]
What the keybinding resolver says for `q`?

**Comment by jordwalke** [comment]
<img width="1052" alt="screen" src="https://cloud.githubusercontent.com/assets/977348/18289775/b2f8ba3a-7435-11e6-8ef9-d74313a83bf2.png">

**Comment by t9md** [comment]
It seems `q` is not properly bounded.

Can you use `j`, `k` to preview each item on preview-pane?

**Comment by jordwalke** [comment]
Yes, `j` and `k` work correctly.

**Comment by t9md** [comment]
![image](https://cloud.githubusercontent.com/assets/155205/18291243/cfaab71e-74c1-11e6-83e3-52d8b7b50f65.png)

How is the search `core:close` result on keybinding section of setting-view.
cmd-, then keybindings in left menu

If you manually map other than `q` key and if it's work, then `q` would be conflicting other keymap.
Please do try&erro and share result, My investigation is very limited(I have no problem with `q`).

**Comment by jordwalke** [comment]
Thanks, I'll try it.

**Comment by t9md** [comment]
To confirm the cause is `q` is conflicting, try following keymap in your `keymap.cson` then check `f7` can close preview-pane.

```
'.preview-pane.project-find-navigation':
  'f7': 'core:close'
```

If OK `q` is definitely conflicting.

Search `q` using keybinding and preview-pane scoped keymap's package.
Disable these suspicious pakages to evaluate it solve `q` issue.

If issue is still remain with only enabling this package, the issue is my package.

**Comment by jordwalke** [comment]
I tried the `f7` mapping and the preview seems to still stay open even after pressing `f7`.

**Comment by t9md** [comment]
Just for confirm.
When you input `q`, you really focused on preview pane. I frequently confuse it by myself.
Maybe I shoud provide close-preview-pane-if-opened command on normal atom-text-editor-scope.

**Comment by jordwalke** [comment]
I am focused on the search results window - the left side of this screen:

<img width="1138" alt="screen shot 2016-09-16 at 4 43 39 pm" src="https://cloud.githubusercontent.com/assets/977348/18604068/c24e0cac-7c2c-11e6-9121-83bb0247b388.png">

**Comment by jordwalke** [comment]
While focused on the left side, pressing `q` closes the results view, but the preview stays open on the right.

**Comment by t9md** [comment]
> closes the results view, but the preview stays open on the right.

This mean 'when you focused on right side text-editor'?

**Comment by jordwalke** [comment]
So results view = the list on the left.
The preview = the source preview on the right (which opened automatically).

I am "focused" on the left side (the results view). I can press j/k and the highlighted line moves up and down - which causes the preview window (on the right) to change the code it's displaying. You can see that in this screenshot, the pane on the left is highlighted blue in the tab bar - which means that's currently focused (correct?). Then I press `q`, and the focused tab on the left closes, but the tab in the right pane remains open.

**Comment by t9md** [comment]
Oh I think I finally understood what you wanted now.
You want close both pane right?
What you are calling the preview pane is just normal text-editor and currently this package not manage to close theae opened editor.
So if you walk through matchs by jk across many files and q to close. All opened files are remain opened, that's expected result.

**Comment by jordwalke** [comment]
Oh, hmm - I would have expected that the "preview pane" that opens is just to show you context of the current highlighted search item in the project search results. I would expect `q` to close them both. The reason is that if I wanted the code to stay open, I would have hit `enter` on the result, to have it open in a new window tab. You can see in my screenshot, `Test.re` is already open in another tab, so the project search leaves me with _two_ copies of that file open even after I hit `q`. I think the pane that opens to the right show really only be to "preview" the code (just provide a quick, temporary view of the search result). Another explicit action should be required to actually open that file for a long period of time IMHO.

**Comment by t9md** [comment]
Yes, understand your point.
It's task to improve this package.
Btw, I rarely use `j` or `k` on result pane.
I normally focused on text-editor while result-pane was opened, and `ctrl-cmd-n` or `ctrl-cmd-p`(need keymap exampled in README) to walk through matches and edit.

**Comment by t9md** [comment]
I modified to open file with `pending` state, which is option when new editor is opened.
If you visit a file only by `project-find-navigation`'s `j` or `k`, it only use one-tab(pending item is replaced when another pending item was opened).

This is much better than opening multiple files.

This package is still very experimental/aggressive hack to find-and-replace.
As I wrote in README.md this package is vulnerable by change of upstream find-and-replace package.

Ideally  I or someone try to merge some of this packages feature to upstream find-and-replace

**Comment by jordwalke** [comment]
It seems that now, when using `j`/`k`, the preview window does not appear next to the results list. I really miss that. Is it a known change? I understand it's difficult to implement, just want to make sure I'm doing everything correct on my end.

**Comment by t9md** [comment]
I think I can close this.
